Add Roles tasks and vars SLES
Icinga/ansible-collection-icinga pull request #158
Opened 2023-05-24 12:42 UTC by dh-roland

For issue: #157 
Add Role Tasks and vars for SUSE

2023-05-24 12:49 UTC, dh-roland commented
Recheck

2023-05-24 13:58 UTC, bobapple commented
@cla-bot check

2023-05-30 13:25 UTC, mkayontour commented on roles/icinga2/tasks/install_on_Suse.yml
Can you add a blank line between the tasks, it looks a bit cleaner and supports the readability.

2023-05-30 13:34 UTC, mkayontour requested changes
Thanks for the PR, eveything looks great so far. Two changes should be made, firstly the cosmetics in the install.yml. And secondly please add a changelog fragment. 

Just create a yaml file in the `changelog/fragments` folder. Naming scheme should be something like `feature_things_change_at_installation.yml` and the content is similar to the following file: https://github.com/Icinga/ansible-collection-icinga/blob/main/changelogs/fragments/feature_monitoring_plugins.yml

Other than that, I'm happy to merge your PR

2023-05-30 15:06 UTC, mkayontour commented on roles/icinga2/tasks/install_on_Suse.yml
Additional can you please use the Ansible FQCN notation for the zypper modules. https://docs.ansible.com/ansible/latest/collections/community/general/zypper_module.html

2023-05-31 07:21 UTC, mkayontour approved these changes

2023-05-31 07:24 UTC, merged

2023-05-31 07:25 UTC, mkayontour commented
I merged the PR, thank you very much for your contribution!