Adds IcingaDB-Web support
Icinga/ansible-collection-icinga pull request #159
Opened 2023-05-26 14:38 UTC by mocdaniel

This PR adds IcingaDB-Web support to the Icingaweb2 role. It sets sane defaults and works on Debian and RHEL.

2023-05-30 13:12 UTC, mkayontour requested changes
Please change the commented sections and then it looks good to me. Thanks

2023-05-30 13:12 UTC, mkayontour commented on roles/icingaweb2/tasks/modules/icingadb_web.yml
Please use the variable `_i2_config_hash` to reduce the amount of templates.

2023-05-30 13:12 UTC, mkayontour commented on roles/icingaweb2/templates/icingadb_config.ini.j2
Should not be used, instead use `modules_config.ini.j2`

2023-06-01 06:44 UTC, mocdaniel commented on roles/icingaweb2/tasks/modules/icingadb_web.yml
Done.

2023-06-01 06:44 UTC, mocdaniel commented on roles/icingaweb2/templates/icingadb_config.ini.j2
Done.

2023-06-01 06:45 UTC, mocdaniel commented
> Please change the commented sections and then it looks good to me. Thanks

I adjusted the role, but I needed to introduce a new file in order to loop over two tasks as a block sequentially.

This was needed because we have to set `_i2_config_hash` for each file to be generated.

2023-06-07 12:58 UTC, mkayontour commented on roles/icingaweb2/tasks/modules/icingadb_web.yml
> +  include_tasks: manage_icingadbweb_config.yml
ansible.builtin.include_tasks

2023-06-07 12:59 UTC, mkayontour requested changes
Can you change the include_tasks to the ansible fqcn name as mentioned in the comments ;).

2023-06-12 07:15 UTC, mocdaniel commented on roles/icingaweb2/tasks/modules/icingadb_web.yml
> +  include_tasks: manage_icingadbweb_config.yml
Done

2023-06-29 09:59 UTC, mkayontour approved these changes

2023-06-29 10:43 UTC, mocdaniel commented
Do you want me to resolve the conflicts @mkayontour?

2023-06-29 11:44 UTC, mkayontour commented
It's ok, I added some stuff and moved some variables. I'll clean up my stuff.

2023-07-03 12:17 UTC, mkayontour approved these changes

2023-07-03 12:20 UTC, merged