Adds password capabilities to icingadb-redis configuration
Icinga/ansible-collection-icinga pull request #202
Opened 2023-10-31 14:30 UTC by mocdaniel

For now we added basic `requirepass` capabilities. We might want to look into other, more advanced available configuration options?

2023-11-07 15:09 UTC, mkayontour requested changes

2023-11-07 15:09 UTC, mkayontour commented on roles/icingadb_redis/templates/icingadb-redis.conf.j2
> +{% if icingadb_redis_password %}
Can you change the if clause to check if the variable is defined? 
`if icingadb_redis_password is defined ` 
Then we don't need the default variable set to `false`.

2023-11-08 09:34 UTC, gianmarco-mameli commented
I'm interested in this feature, actually I was thinking to add the config myself, if you need help I'm available

2023-11-10 09:45 UTC, mkayontour approved these changes
thanks for the PR, I'll merge it.

2023-11-10 09:46 UTC, merged