support Raspbian armhf repos
Icinga/ansible-collection-icinga pull request #203
Opened 2023-11-02 14:51 UTC by gianmarco-mameli

add support for configure Raspbian armhf repos

2023-11-03 08:55 UTC, gianmarco-mameli commented
Hi, I've completed the procedure to sign the CLA, thanks

2023-11-03 09:07 UTC, mkayontour requested changes
Thanks for the PR.
I don't have a raspberry at the moment to check which variables are available but, it think it is possible to include raspbian in the first lookup. 
`ansible_os_family` should be **debian** i think, afterwards you can create a file in `vars/` named, 
`Debian-Raspbian.yml`.

2023-11-03 09:07 UTC, mkayontour commented on roles/repos/tasks/main.yml
> +
Would it not be easier if we use the variable `ansible_lsb.id` in the first lookup? 
Thats why there's a lookup in the first place. 

Example:
```
      files:
        - "{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_lsb.id }}.yml"
        - "{{ ansible_os_family }}.yml"
```
If theres a better place as second to last, please suggest a other place. ;)

2023-11-03 09:16 UTC, gianmarco-mameli commented on roles/repos/tasks/main.yml
> +
Hi, you're right, as soon as the Debian.yml doesn't exist the last variable file imported il Debian-Raspbian.yml overriding correctly the repos. I'm going to commit the changes. Thanks

2023-11-03 09:49 UTC, gianmarco-mameli commented
I don't know why the CLA is failing

2023-11-03 09:55 UTC, martialblog commented
@bobapple  to the rescue

2023-11-03 13:28 UTC, bobapple commented
@cla-bot check

2023-11-03 13:33 UTC, gianmarco-mameli commented
Thanks

2023-11-07 14:35 UTC, merged

2023-11-07 14:35 UTC, mkayontour commented
Thanks again for your contribution!