added missing quotes to ticket delegation
Icinga/ansible-collection-icinga pull request #250
Opened 2023-12-29 10:51 UTC by fl0wx

Added missing quotes to ticket delegation. Currently, the ticket creation fails with the following error message:

```
TASK [icinga.icinga.icinga2 : delegate ticket request to master] ***********************************************************************************************************************************************************************************************************************************************************
changed: [host1.local -> host0.local] => {"changed": true, "cmd": "icinga2 pki ticket --cn \"host1.local --salt XXXXXXXX\"", "delta": "0:00:00.062976", "end": "2023-12-29 11:33:07.761888", "msg": "", "rc": 0, "start": "2023-12-29 11:33:07.698912", "stderr": "", "stderr_lines": [], "stdout": "fc043b935aacd292b742b0aaecd63e9055c16c95", "stdout_lines": ["fc043b935aacd292b742b0aaecd63e9055c16c95"]}

TASK [icinga.icinga.icinga2 : get certificate] *****************************************************************************************************************************************************************************************************************************************************************************
fatal: [host1.local]: FAILED! => {"changed": true, "cmd": "icinga2 pki  request --ticket \"fc043b935aacd292b742b0aaecd63e9055c16c95\" --host \"host0.local\" --port \"5665\" --ca \"/var/lib/icinga2/certs/ca.crt\" --key \"/var/lib/icinga2/certs/host1.local.key\" --trustedcert \"/var/lib/icinga2/certs/trusted-master.crt\"  --cert \"/var/lib/icinga2/certs/host1.local.crt\"", "delta": "0:00:00.130217", "end": "2023-12-29 11:33:09.363278", "msg": "non-zero return code", "rc": 1, "start": "2023-12-29 11:33:09.233061", "stderr": "", "stderr_lines": [], "stdout": "information/cli: Writing CA certificate to file '/var/lib/icinga2/certs/ca.crt'.\ncritical/cli: !!! Invalid ticket for CN 'host1.local'.", "stdout_lines": ["information/cli: Writing CA certificate to file '/var/lib/icinga2/certs/ca.crt'.", "critical/cli: !!! Invalid ticket for CN 'host1.local'."]}
```

the addition of the new quotes changes the command to an actual working command:

OLD: icinga2 pki ticket --cn \"host1.local --salt XXXXXXXX\"
NEW: icinga2 pki ticket --cn \"host1.local\" --salt \"XXXXXXXX\"

2023-12-29 15:08 UTC, mocdaniel approved these changes
Thanks a lot, this slipped our attention.
~LGTM!~ *Edit*: Please see comment below.

2023-12-29 15:10 UTC, mocdaniel requested changes
Almost forgot: Could you please add a changelog fragment? This makes it easier for us to track changes, fixes, etc. and attribute them to contributors.

Information on how to do it can be found [here](https://github.com/Icinga/ansible-collection-icinga/blob/main/CONTRIBUTING.md#changelog-fragments), with some recent examples [here](https://github.com/Icinga/ansible-collection-icinga/commit/ff0fcfdc70b41887f959ec80cc7aff41d97ad90e).

2023-12-29 15:17 UTC, fl0wx commented
done :)

2023-12-29 15:18 UTC, mocdaniel commented
@bobapple can you check whether the CLA has been signed successfully?

2023-12-29 15:24 UTC, fl0wx commented
@mocdaniel  i signed it just now. can you rerun the check?

2023-12-29 15:45 UTC, mocdaniel commented
Unfortunately, I can't, hence the ping above :) This will get merged after the weekend, probably.

2023-12-29 15:45 UTC, mocdaniel approved these changes

2023-12-31 12:27 UTC, bobapple commented
@cla-bot check

2023-12-31 12:27 UTC, bobapple commented
@cla-bot check

2023-12-31 12:31 UTC, mocdaniel commented
Thanks a lot for your contribution @fl0wx!

2023-12-31 12:31 UTC, merged