fix #40 RHEL/Centos: manage icinga2-selinux package
Icinga/ansible-collection-icinga pull request #48
Opened 2021-07-29 13:15 UTC by lbetz

2021-08-12 14:22 UTC, lazyfrosch commented on roles/icinga2/tasks/install_on_RedHat.yml
> +  when: ansible_selinux.status == "enabled"
```suggestion
  when: ansible_selinux is defined and ansible_selinux.status == "enabled"
```

2021-08-12 14:22 UTC, lazyfrosch requested changes
Good idea, I would check if the ansible_selinux fact is even present

2021-08-19 05:54 UTC, mkayontour commented
This is right, to avoid the failure of the role when the ansible_selinux.state is missing. @lbetz are you happy with this?

2021-08-19 13:17 UTC, lbetz commented
@mkayontour sure!

2021-08-19 13:17 UTC, merged